name: Embed

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'  # JST 7:00
#    - cron: '0 * * * *'  # every hours

env:
  SID: ${{ secrets.SID }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
  TZ: 'Asia/Tokyo'

jobs:
  build:
    permissions:
      contents: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true        

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.4'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Download Latest Release  if exists (get PROJECT_NAME.pickle for cache)
        run: python download_latest_release/main.py

      - name: Do Pioneering and write (PROJECT_NAME.json to Scrapbox)
        run: python write_to_scrapbox/main.py --pioneer



